### ISSUE TITLE
Add loading icon in the search bar.

### ISSUE THREAD

**Issue by suryapratapsinghsuryavanshi** [suryapratapsinghsuryavanshi/NASA-Media-Search#5]
The current web page works fine but if we search for anything no progress bar appears you can add a progress bar or `loading icon`.

**Comment by MuhammadTanveer94** [comment]
@suryapratapsinghsuryavanshi could you please assign me this issue?

**Comment by suryapratapsinghsuryavanshi** [comment]
Yeah @MuhammadTanveer94, I assign this issue to you.

**Comment by MuhammadTanveer94** [comment]
@suryapratapsinghsuryavanshi please look into this PR https://github.com/suryapratapsinghsuryavanshi/NASA-Media-Search/pull/6. Kindly merge it.
