### ISSUE TITLE
Add PopUp Box

### ISSUE THREAD

**Issue by suryapratapsinghsuryavanshi** [suryapratapsinghsuryavanshi/NASA-Media-Search#7]
After getting the search result if we click on any search result then a pop-up should open.
Link: https://xd.adobe.com/view/3034ede0-57a5-4062-93f0-aa8da7b50923-6567/

**Comment by MuhammadTanveer94** [comment]
@suryapratapsinghsuryavanshi i would love to work on this.

**Comment by suryapratapsinghsuryavanshi** [comment]
@MuhammadTanveer94
I am glad to see you in this issue section, please do your work create a PR we will definitely merge it :)

**Comment by MuhammadTanveer94** [comment]
@suryapratapsinghsuryavanshi i have created reusable popup component. https://github.com/suryapratapsinghsuryavanshi/NASA-Media-Search/pull/8 please into this PR. kindly merge it.
